Repository AppiumTestDistribution/appium-wait-plugin, pull requests merged in 2023-06, with the labels that each got.

#77 fix XcuiTest run
  package-lock.json
  package.json
  src/element.js
Labels: bump:minor

#79 make timeout override to be partial and enable enable check exclusion.
  .azure-template/bootstrap.yml
  README.md
  __tests__/e2e/plugin.spec.js
  __tests__/plugin.spec.js
  azure-pipelines.yml
  package-lock.json
  package.json
  src/element.js
  src/plugin.js
Labels: bump:major

#82 add excludeEnabledCheck to cliargs
  .github/workflows/npm-publish.yml
  README.md
  azure-pipelines.yml
  package-lock.json
  package.json
Labels: bump:minor

#84 release
  package-lock.json
Labels: bump:patch

#85 Publish
  package-lock.json
  package.json
Labels: bump:patch
